name: Build Web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: emscripten/emsdk:6.0.7

    steps:
      - name: Download repository
        uses: actions/checkout@v5

      - name: Verify Emscripten
        run: emcc --version
      - name: Build web version
        run: |
          mkdir -p build/web
          emcc Umbra/Main.c --use-port=sdl2 -o build/web/index.html
          ls -la build/web